name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: bootstrap and configure
      run: ./bootstrap && ./configure
    - name: make
      run: make
    - name: make distcheck
      run: make distcheck
