name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-16.04]
    
    steps:
    - uses: actions/checkout@v1
    - name: Install build tools
      if: matrix.os == 'macos-latest'
      run: brew install autoconf automake libtool pkg-config
    - name: bootstrap and configure
      run: ./bootstrap && ./configure
    - name: make
      run: make
    - name: make distcheck
      run: make distcheck

  build_msvc:
    name: Build (MSVC 2019)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\build\vc10\libupnp.vcxproj /p:PlatformToolset=v142
